server:
  # you can only hit this from within localhost
  host: 127.0.0.1
  port: 3555
# You'll need your own instance hosting cardano-graphql
cardano-graphql:
  host: X
  port: X
postgres:
  database: X
  host: X
  username: X
  password: X
now-payments:
  api-key: X
mocked: false
