server:
  # leave host blank or server will only accept calls from localhost
  host: 
  port: 3555
cardano-graphql:
  host: http://127.0.0.1
  port: 3100
now-payments:
  api-key: X
postgres:
  db:
  host:
  user:
  password:
mocked: false
